// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYl619Bl7KNdRnnRX-_1aVw6UpC4jn71w',
    appId: '1:114152481636:web:0e61704630067c11a6d071',
    messagingSenderId: '114152481636',
    projectId: 'vistacall-83230',
    authDomain: 'vistacall-83230.firebaseapp.com',
    storageBucket: 'vistacall-83230.firebasestorage.app',
    measurementId: 'G-QT72MYN1Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsRXoy0lW27eX1jO_g8q72qIfYe8rkGCg',
    appId: '1:114152481636:android:faa39073ee299bada6d071',
    messagingSenderId: '114152481636',
    projectId: 'vistacall-83230',
    storageBucket: 'vistacall-83230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiznEBhFUcnEJ0oxnfYCIp5dn93Rp9vzI',
    appId: '1:114152481636:ios:8d99ff58c355103ca6d071',
    messagingSenderId: '114152481636',
    projectId: 'vistacall-83230',
    storageBucket: 'vistacall-83230.firebasestorage.app',
    androidClientId: '114152481636-1etrhmnds66pnlbdll8rrqo7stfs9i01.apps.googleusercontent.com',
    iosClientId: '114152481636-5u6fekvie2cebqre5e0t9cet2al2sdq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.vistacall',
  );
}
